# Homebrew formula for farwatch CLI
#
# Install: brew install yipjunkai/farwatch/farwatch
#
# Maintenance:
# - This file is auto-regenerated by CI (.github/workflows/release.yml)
#   on every tag push. Version and SHA256 hashes are computed automatically.
# - The install script (install.sh) is the other install path and requires
#   no updates on release.
# - Do not edit manually — changes will be overwritten by the next release.

class Farwatch < Formula
  desc "Mirror local AI terminal sessions to remote clients with E2E encryption"
  homepage "https://github.com/yipjunkai/farwatch"
  license any_of: ["MIT", "Apache-2.0"]
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/yipjunkai/farwatch/releases/download/v0.1.0/farwatch-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "cfaa954fe30533edf5e319557e685173f5d0ef3d7ec2a4892d59564a00ed7545"
    end

    on_arm do
      url "https://github.com/yipjunkai/farwatch/releases/download/v0.1.0/farwatch-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "ea94423c415547cec0dd1d94658b95514d1881a654f4b48b2f4ba4c5e27b7881"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yipjunkai/farwatch/releases/download/v0.1.0/farwatch-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "63b7a10c1133e26426e6994b8dfaec8d0af22c52cf2eed0ff1ff418e00dcbe98"
    end

    on_arm do
      url "https://github.com/yipjunkai/farwatch/releases/download/v0.1.0/farwatch-v0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "9895b8bb669f46c4fe429ddc03e6cbf5fc69bb0553a08fe4ee210a04cf133c27"
    end
  end

  def install
    bin.install "farwatch"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/farwatch --version")
  end
end
